Sigmoid Activation

In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Test the sigmoid function
x = np.array([1, 2, 3])
print(sigmoid(x))


[0.73105858 0.88079708 0.95257413]


ReLU Activation


In [2]:
def relu(x):
    return np.maximum(0, x)

# Test the ReLU function
x = np.array([-1, 0, 1])
print(relu(x))


[0 0 1]


Tanh Activation

In [3]:
def tanh(x):
    return np.tanh(x)

# Test the Tanh function
x = np.array([-1, 0, 1])
print(tanh(x))


[-0.76159416  0.          0.76159416]


GELU Activation


In [4]:
def gelu(x):
    return 0.5 * x * (1 + np.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * x**3)))

# Test the GELU function
x = np.array([-1, 0, 1])
print(gelu(x))


[-0.15880801  0.          0.84119199]


Loss Functions Cross-Entropy Loss

In [5]:
def cross_entropy_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Test the cross-entropy loss function
y_true = np.array([1, 0, 1])
y_pred = np.array([0.9, 0.1, 0.8])
print(cross_entropy_loss(y_true, y_pred))


0.14462152754328741


Mean Squared Error (MSE) Loss

In [6]:
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

# Test the MSE loss function
y_true = np.array([1, 2, 3])
y_pred = np.array([0.9, 2.1, 2.8])
print(mse_loss(y_true, y_pred))


0.020000000000000028


Custom Activation and Loss Functions

In [7]:
def custom_activation(x):
    return np.sin(x) + np.cos(x)

# Test the custom activation function
x = np.array([0, np.pi/4, np.pi/2])
print(custom_activation(x))


[1.         1.41421356 1.        ]


Custom Loss Function

In [8]:
def custom_loss(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

# Test the custom loss function
y_true = np.array([1, 2, 3])
y_pred = np.array([0.9, 2.1, 2.8])
print(custom_loss(y_true, y_pred))


0.13333333333333341
